services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: blog-graphql-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - blog-graphql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog-graphql-db -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  blog-graphql: